import { test, expect } from "@playwright/test";

test("Peringatan data lama tidak menimpa peta HP", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.clock.install();
  await page.goto("/login/");
  await page.getByRole("button", { name: "Lihat pratinjau" }).click();
  await page.locator(".bottom-nav").getByRole("button", { name: "Peta", exact: true }).click();
  await expect(page.locator(".leaflet-container")).toBeVisible();
  await page.clock.fastForward(16 * 60000);
  const notice = page.getByText(/Data contoh terakhir lebih dari 15 menit/);
  await expect(notice).toBeVisible();
  const metadata = await page.locator(".data-meta").boundingBox();
  const warning = await notice.boundingBox();
  const map = await page.getByRole("region", { name: "Peta titik monitoring", exact: true }).boundingBox();
  expect(warning!.y).toBeGreaterThanOrEqual(metadata!.y + metadata!.height);
  expect(map!.y).toBeGreaterThanOrEqual(warning!.y + warning!.height);
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight + 1)).toBe(true);
  await page.screenshot({ path: "test-results/map-mobile-stale.png" });
});

test("Filter koneksi dan pencarian peta bekerja bersama", async ({ page }) => {
  await page.goto("/login/");
  await page.getByRole("button", { name: "Lihat pratinjau" }).click();
  await page.locator(".sidebar").getByRole("button", { name: "Peta", exact: true }).click();
  const list = page.getByRole("region", { name: "Daftar titik monitoring" });
  await list.getByRole("button", { name: "Gedung", exact: true }).click();
  await expect(list.getByText("Menampilkan 3 dari 4 titik")).toBeVisible();
  await expect(list.getByRole("button", { name: /DSIH/ })).toBeVisible();
  await expect(list.getByRole("button", { name: /Sumur Rektorat/ })).toHaveCount(0);
  await list.getByRole("textbox", { name: "Cari titik" }).fill("Sumur Rektorat");
  await expect(list.getByText("Tidak ada titik yang cocok.")).toBeVisible();
  await list.getByRole("button", { name: "Sumur", exact: true }).click();
  await list.getByRole("button", { name: /Sumur Rektorat/ }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
});

test("Panel peta HP dapat diperluas, dicari, dan membuka detail", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/login/");
  await page.getByRole("button", { name: "Lihat pratinjau" }).click();
  await page.locator(".bottom-nav").getByRole("button", { name: "Peta", exact: true }).click();
  await expect(page.locator(".leaflet-container")).toBeVisible();
  const list = page.getByRole("region", { name: "Daftar titik monitoring" });
  const before = await list.boundingBox();
  const handle = await page.getByRole("button", { name: "Perluas daftar titik" }).boundingBox();
  await page.mouse.move(handle!.x + handle!.width / 2, handle!.y + handle!.height / 2);
  await page.mouse.down();
  await page.mouse.move(handle!.x + handle!.width / 2, handle!.y - 100, { steps: 8 });
  expect((await list.boundingBox())!.height).toBeGreaterThan(before!.height);
  await page.mouse.up();
  await expect(page.getByRole("button", { name: "Kecilkan daftar titik" })).toBeVisible();
  const upper = await page.getByRole("button", { name: "Kecilkan daftar titik" }).boundingBox();
  await page.mouse.move(upper!.x + upper!.width / 2, upper!.y + upper!.height / 2);
  await page.mouse.down();
  await page.mouse.move(upper!.x + upper!.width / 2, upper!.y + 150, { steps: 8 });
  await page.mouse.up();
  await expect(page.getByRole("button", { name: "Perluas daftar titik" })).toBeVisible();
  expect((await list.boundingBox())!.height).toBeCloseTo(before!.height, 0);
  const lower = await page.getByRole("button", { name: "Perluas daftar titik" }).boundingBox();
  await page.mouse.move(lower!.x + lower!.width / 2, lower!.y + 12);
  await page.mouse.down();
  await page.mouse.move(lower!.x + lower!.width / 2, lower!.y + 210, { steps: 8 });
  await page.mouse.up();
  expect((await list.boundingBox())!.height).toBeCloseTo(104, 0);
  await page.getByRole("button", { name: "Cari dan filter titik" }).click();
  await expect(page.getByRole("textbox", { name: "Cari titik" })).toBeVisible();
  const after = await list.boundingBox();
  expect(after!.height).toBeGreaterThan(before!.height);
  await page.getByRole("textbox", { name: "Cari titik" }).fill("DSIH");
  await list.getByRole("button", { name: "Gedung", exact: true }).click();
  await list.getByRole("button", { name: /DSIH/ }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  const grip = await page.getByRole("button", { name: "Perluas detail titik" }).boundingBox();
  await page.mouse.move(grip!.x + grip!.width / 2, grip!.y + 12);
  await page.mouse.down();
  await page.mouse.move(grip!.x + grip!.width / 2, 800, { steps: 12 });
  await page.mouse.up();
  expect((await page.getByRole("dialog").boundingBox())!.height).toBeCloseTo(104, 0);
  await page.getByRole("button", { name: "Perluas detail titik" }).click();
  expect((await page.getByRole("dialog").boundingBox())!.height).toBeGreaterThan(600);
  await page.getByRole("button", { name: "Tutup detail" }).click();
  await page.getByRole("button", { name: "Kecilkan daftar titik" }).click();
  await expect(page.getByRole("button", { name: "Perluas daftar titik" })).toBeVisible();
});
