import { expect, test } from "@playwright/test";
for (const width of [360, 390, 430, 768, 1366, 1440, 1920]) {
  test(`Monitoring cards and dialogs at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 });
    const errors: string[] = [];
    page.on("pageerror", e => errors.push(e.message));
    await page.goto("/demo/admin/");
    if (width <= 640) await page.locator(".bottom-nav").getByRole("button", { name: "Kelola", exact: true }).click();
    await page.locator(width <= 640 ? ".content" : ".sidebar").getByRole("button", { name: width <= 640 ? "Titik Monitoring Kelola Sumur dan Gedung" : "Kelola Titik Monitoring" }).click();
    const card = page.getByRole("article", { name: "Gedung Rektorat", exact: true });
    await expect(card).toBeVisible();
    const columns = await card.evaluate(element => getComputedStyle(element.parentElement!).gridTemplateColumns.split(" ").length);
    expect(columns).toBe(width <= 768 ? 1 : 3);
    const editBounds = await card.getByRole("button", { name: "Edit Gedung Rektorat" }).boundingBox();
    expect(editBounds!.height).toBeGreaterThanOrEqual(44);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: `test-results/monitoring-${width}.png`, fullPage: true });
    await card.getByRole("button", { name: "Atur Gedung Rektorat" }).click();
    const dialog = page.getByRole("dialog");
    await expect(dialog).toBeVisible();
    const toggle = dialog.getByRole("switch");
    await toggle.focus();
    const before = await toggle.isChecked();
    await page.keyboard.press("Space");
    expect(await toggle.isChecked()).toBe(!before);
    await page.screenshot({ path: `test-results/monitoring-settings-${width}.png` });
    await page.keyboard.press("Escape");
    await expect(dialog).not.toBeVisible();
    await expect(card.getByRole("button", { name: "Atur Gedung Rektorat" })).toBeFocused();
    await card.getByRole("button", { name: "Edit Gedung Rektorat" }).click();
    await expect(dialog.getByLabel("Jumlah pegawai", { exact: true })).toBeVisible();
    await dialog.getByLabel("Lokasi", { exact: true }).fill("Lokasi dengan deskripsi panjang ".repeat(3));
    await page.screenshot({ path: `test-results/monitoring-edit-${width}.png` });
    await dialog.getByRole("button", { name: "Simpan", exact: true }).click();
    await expect(dialog).not.toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.getByRole("button", { name: "Tambah titik", exact: true }).click();
    await expect(dialog.getByLabel("Jumlah pegawai", { exact: true })).toHaveCount(0);
    await dialog.getByLabel("Nama", { exact: true }).fill("Sumur UI");
    await dialog.getByLabel("Kode titik", { exact: true }).fill("UI-TEST");
    await dialog.getByLabel("Lokasi", { exact: true }).fill("Area uji");
    await dialog.getByRole("switch", { name: "Titik monitoring" }).uncheck();
    await dialog.getByRole("button", { name: "Simpan", exact: true }).click();
    const well = page.getByRole("article", { name: "Sumur UI", exact: true });
    await expect(well).toContainText("Nonaktif");
    await expect(well.getByRole("button", { name: /Atur/ })).toHaveCount(0);
    expect(errors).toEqual([]);
  });
}
